feat: Improved compliance of URL object
awslabs/llrt pull request #409
Opened 2024-06-05 11:53 UTC by nabetti1720

### Description of changes

Add the following methods to improve the compliance of `URL` Object.
See also. https://url.spec.whatwg.org/#dom-url-parse

- URL.parse()

### Checklist

- [x] Created unit tests in `tests/unit` and/or in Rust for my feature if needed
- [x] Ran `make fix` to format JS and apply Clippy auto fixes
- [x] Made sure my code didn't add any additional warnings: `make check`
- [x] Updated documentation if needed ([API.md](API.md)/[README.md](README.md)/Other)

_By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice._

2024-06-06 18:07 UTC, richarddavison requested changes
Thanks for the PR, just a tiny improvement and I'm happy :)

2024-06-06 23:00 UTC, nabetti1720 commented on llrt_core/src/modules/http/url.rs
> +            let base_string = match get_string(&ctx.clone(), base) {
It is a remnant from the days of trial and error. Fixed.

2024-06-06 23:00 UTC, nabetti1720 commented on llrt_core/src/modules/http/url.rs
> +                Err(_) => return Null.into_js(&ctx).unwrap(),
This has also been corrected. Please review.

2024-06-07 04:25 UTC, richarddavison approved these changes
Awesome thanks!

2024-06-07 06:09 UTC, merged