Typing
awslabs/llrt pull request #483
Opened 2024-07-15 20:19 UTC by Sytten

NOT READY

### Description of changes

Adding a typing package to be published on NPM. We will then push a placeholder package in DefinitelTyped for `@types/llrt` which will re-export those types (this what Bun does to keep control over the typing in their repo).

### Checklist

- [x] Created unit tests in `tests/unit` and/or in Rust for my feature if needed
- [x] Ran `make fix` to format JS and apply Clippy auto fixes
- [x] Made sure my code didn't add any additional warnings: `make check`
- [x] Updated documentation if needed ([API.md](API.md)/[README.md](README.md)/Other)

_By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice._

2024-07-16 11:38 UTC, richarddavison requested changes
Outstanding work!!!

2024-07-16 11:38 UTC, richarddavison commented on types/buffer.d.ts
> +  export type BufferEncoding = "utf8" | "base64" | "iso88591" | "hex";
utf16le is also supported

2024-07-16 13:46 UTC, Sytten commented on types/buffer.d.ts
> +  export type BufferEncoding = "utf8" | "base64" | "iso88591" | "hex";
True that was added recently

2024-07-16 17:48 UTC, richarddavison approved these changes

2024-07-17 16:57 UTC, richarddavison approved these changes

2024-07-17 17:45 UTC, Sytten commented
Waiting on #480 to be merged before I finish this

2024-07-18 17:24 UTC, Sytten commented
Typing should be done now

2024-07-19 15:26 UTC, richarddavison approved these changes
Thanks for this amazing contribution!

2024-07-19 15:27 UTC, merged