Improve features and CI
awslabs/llrt pull request #576
Opened 2024-09-04 14:23 UTC by Sytten

### Description of changes

- Add CI for each feature
- Remove tokio full and use scoped features

### Checklist

- [x] Created unit tests in `tests/unit` and/or in Rust for my feature if needed
- [x] Ran `make fix` to format JS and apply Clippy auto fixes
- [x] Made sure my code didn't add any additional warnings: `make check`
- [x] Added relevant type info in `types/` directory
- [x] Updated documentation if needed ([API.md](API.md)/[README.md](README.md)/Other)

_By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice._

2024-09-04 21:05 UTC, richarddavison requested changes
Thanks! Some minor comments

2024-09-04 21:19 UTC, Sytten commented on .github/workflows/build-modules.yml
> +          features=("buffer"
I know, I tried to fetch them from the manifest but optional dependencies also create features so it's kinda not possible :/

2024-09-04 21:22 UTC, Sytten commented on llrt_modules/Cargo.toml
> +url_crate = { version = "2.5", package = "url", optional = true }
You can lock that on the user side IMO, but I can also add a `<2.5.2`. The point is mostly that someone using 2.5.0 should be able to use it, even 2.x should be fine.

2024-09-05 05:38 UTC, richarddavison approved these changes

2024-09-05 05:38 UTC, merged