support require json file
awslabs/llrt pull request #580
Opened 2024-09-08 06:05 UTC by ahaoboy

### Description of changes
Support require json files

```js
console.log( require('package.json') )

```
### Checklist

- [x] Created unit tests in `tests/unit` and/or in Rust for my feature if needed
- [x] Ran `make fix` to format JS and apply Clippy auto fixes
- [x] Made sure my code didn't add any additional warnings: `make check`
- [ ] Added relevant type info in `types/` directory
- [ ] Updated documentation if needed ([API.md](API.md)/[README.md](README.md)/Other)

2024-09-08 18:10 UTC, richarddavison requested changes
This is a great addition but should be done at import level instead of only supporting require.

2024-09-09 10:10 UTC, richarddavison commented
> > This is a great addition but should be done at import level instead of only supporting require.
> 
> Do you mean support for `import a from './a.json'`? This should implement a JSONLoader, but nodejs not support this syntax

It does not but does through import assertions. I think we can allow it in LLRT as well.
 Also left another comment in the PR regarding evaluation of JSON.

2024-09-09 10:11 UTC, richarddavison requested changes

2024-09-09 10:11 UTC, richarddavison commented on llrt_core/src/vm.rs
> +                let v: Value = ctx.eval(format!("({source})"))?;
This will be evaluated as JavaScript. Please use `json_parse` instead.

2024-09-09 10:39 UTC, ahaoboy commented
> It does not but does through import assertions. I think we can allow it in LLRT as well.


This may be more troublesome than expected due to the confusing behavior of cjs and esm

If you use the json file as a js file that exports a js object by default
```json
{ "a": 1 }
```
```js
export default { "a": 1 } 
```
Then what we get is an object like this
```
const a = require('./a.json')

// { default: { a: 1} }
```

2024-09-09 10:54 UTC, richarddavison commented
> If you use the json file as a js file that exports a js object by default

What do you mean by this? :)

2024-09-09 11:25 UTC, ahaoboy commented
> What do you mean by this? :)

```rust
use rquickjs::{loader::Loader, Ctx, Error, Module, Result};

#[derive(Debug)]
pub struct JSONLoader;

impl Loader for JSONLoader {
    fn load<'js>(&mut self, ctx: &Ctx<'js>, path: &str) -> Result<Module<'js>> {
        if !path.ends_with(".json") {
            return Err(Error::new_loading(path));
        }
        let source = std::fs::read_to_string(path)?;
        Module::declare(ctx.clone(), path, format!("export default ({source})"))
    }
}

```

2024-09-09 13:54 UTC, richarddavison commented
Right I see what you mean. It might be better to have two separate implementations since there is no way to return an already created object from a module.

I would for the require function use `json_parse` and for the json loader use:

  `Module::declare(ctx.clone(), path, ["export default ", &source].concat())`

2024-09-10 12:15 UTC, richarddavison approved these changes

2024-09-10 12:16 UTC, merged