feat: Support imports field in package.json
awslabs/llrt pull request #680
Opened 2024-11-15 13:11 UTC by nabetti1720

### Issue # (if available)

Closed #677

### Description of changes

This corresponds to basic loading of the imports field in package.json.

import:
```javascript
//  index19.js
import chalk from 'chalk';
console.log(chalk.blue('Hello world!'));
```
```
% llrt index19.js
Hello world!
```

require:
```javascript
//  index19.js
const chalk = require('chalk');
console.log(chalk.blue('Hello world!'));
```
```
% llrt index19.js
Hello world!
```

### Checklist

- [x] Created unit tests in `tests/unit` and/or in Rust for my feature if needed
- [x] Ran `make fix` to format JS and apply Clippy auto fixes
- [x] Made sure my code didn't add any additional warnings: `make check`
- [x] Added relevant type info in `types/` directory
- [x] Updated documentation if needed ([API.md](API.md)/[README.md](README.md)/Other)

_By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice._

2024-11-15 13:38 UTC, richarddavison requested changes
Thanks, some minor comments!

2024-11-15 13:38 UTC, richarddavison commented on llrt_core/src/module_loader/resolver.rs
> +    match find_the_closest_package_scope(dir) {
Rather than matching on none we can do `if let Some(path) = ...`

2024-11-15 13:38 UTC, richarddavison commented on llrt_core/src/module_loader/resolver.rs
> +    let package_json: BorrowedValue;
why are these defined outside condition?

2024-11-15 13:38 UTC, richarddavison commented on llrt_core/src/module_loader/resolver.rs
> +            }
This check seems redundant as we check the same thing in `package_imports_resolve`. Please remove.

2024-11-15 20:31 UTC, richarddavison approved these changes

2024-11-15 20:31 UTC, merged

2024-11-18 07:18 UTC, ahaoboy commented
@nabetti1720  llrt is a runtime similar to nodejs. Why does llrt prioritize loading browser instead of node?

For example, in chalk, colors are only displayed in node mode.

```
	"imports": {
		"#ansi-styles": "./source/vendor/ansi-styles/index.js",
		"#supports-color": {
			"node": "./source/vendor/supports-color/index.js",
			"default": "./source/vendor/supports-color/browser.js"
		}
	},
```

```
import chalk from "chalk";

console.log(chalk.blue(1))
```

2024-11-18 09:13 UTC, nabetti1720 commented
> @nabetti1720 llrt is a runtime similar to nodejs. Why does llrt prioritize loading browser instead of node?

@ahaoboy , LLRT is a runtime similar to Node.js, but we are not aiming for compatibility with Node.js. On the other hand, we are aiming for compatibility with WinterCG, a WebAPI standard.

For that reason, when searching the "exports" and "imports" fields in package.json, we explicitly exclude the "node" hierarchy from the search, and at the same time control it to prioritize "browser".

In response to this point, I thought it would be a good idea to add a switch to search for "node" in the field search logic, which is currently hard-coded.

The question then would be which should be the default behavior. What do you think, @richarddavison ?