Improve resolve on windows
awslabs/llrt pull request #689
Opened 2024-11-18 10:20 UTC by ahaoboy

### Description of changes

The following test fails on Windows due to the path separator

```
  _require(`${CWD}/fixtures/test_modules/test-uuid.js`);
```

### Checklist

- [x] Created unit tests in `tests/unit` and/or in Rust for my feature if needed
- [x] Ran `make fix` to format JS and apply Clippy auto fixes
- [x] Made sure my code didn't add any additional warnings: `make check`
- [ ] Added relevant type info in `types/` directory
- [ ] Updated documentation if needed ([API.md](API.md)/[README.md](README.md)/Other)

2024-11-18 10:41 UTC, richarddavison requested changes

2024-11-18 10:41 UTC, richarddavison commented on llrt_core/src/module_loader/resolver.rs
> +        })
We have a "to_abs_path" used by `require_resolve` in various places. Use that method inside of require resolve where this case isn't covered!

2024-11-18 13:47 UTC, ahaoboy commented
> The results returned by `require_resolve()` (build-in module name, bytecode cache name, absolute path including search results from package.json, presence or absence of prefix used on the loader side, etc.) vary, so I think it's difficult to judge here.
> 
> I'll take a look at this if you don't mind. :)

The logic is indeed a bit complicated, and I'm not sure whether it should be handled here. If there is a better way, you can directly submit a new PR

2024-11-18 13:59 UTC, nabetti1720 commented
@ahaoboy , This issue was addressed in #690. We have confirmed that the Require tests pass at least in windows-build.

<img width="800" alt="image" src="https://github.com/user-attachments/assets/4f6d996f-05fa-4d8c-9e78-bbcea903b0c4">

2024-11-19 02:38 UTC, nabetti1720 commented
@ahaoboy, #690 has been merged into mainline, so this PR is no longer needed. :)

2024-11-19 03:19 UTC, closed without merging