support repl
awslabs/llrt pull request #693
Opened 2024-11-19 06:44 UTC by ahaoboy

### Description of changes

Adding a simple repl mode

https://nodejs.org/en/learn/command-line/how-to-use-the-nodejs-repl

https://github.com/DelSkayn/rquickjs/blob/master/examples/rquickjs-cli/src/main.rs

### Checklist

- [ ] Created unit tests in `tests/unit` and/or in Rust for my feature if needed
- [ ] Ran `make fix` to format JS and apply Clippy auto fixes
- [ ] Made sure my code didn't add any additional warnings: `make check`
- [ ] Added relevant type info in `types/` directory
- [ ] Updated documentation if needed ([API.md](API.md)/[README.md](README.md)/Other)

_By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice._

2024-11-19 16:36 UTC, richarddavison requested changes
Cool idea, I like it! Some minor comment comments!

2024-11-19 16:36 UTC, richarddavison commented on llrt_core/src/vm.rs
> +                let js_log: Function = console.get("log")?;
We can call these methods directly from rust and print. Check the console module.

2024-11-19 16:36 UTC, richarddavison commented on llrt_core/src/vm.rs
> +                    let mut input = String::new();
We don't need to create a new string very time. We can create one outside the loop and clear it.

2024-11-19 16:36 UTC, richarddavison commented on llrt_core/src/vm.rs
> +                    print!("> ");
Maybe we also should print the version header? (see version method).

2024-11-19 16:36 UTC, richarddavison commented on llrt_core/src/vm.rs
> +                        .unwrap_or_else(|err| println!("{err}"));
I think the right approach here would be to evaluate the code and return value and pass that value to format method and write to std out

2024-11-20 06:52 UTC, richarddavison requested changes
Almost there! Just a minor change

2024-11-20 06:52 UTC, richarddavison commented on llrt_core/src/vm.rs
> +                        Ok(v) => console::log_std_out(
Call `pub fn format` in console instead to get the formated string back. Then do `println` or `eprintln` (for exception) with that string.

2024-11-20 10:08 UTC, richarddavison requested changes
Some suggestions to simplify. Would also be great if we can extract the repl inner logic to an own file and pass input and output to it. That way we can make it testable from rust.

2024-11-20 10:08 UTC, richarddavison commented on llrt_core/src/vm.rs
> +                    match ctx.eval::<Value, _>(input.as_bytes()) {
This still needs a bit of work. Something like this (pseudo code):
```rust
match ctx.eval::<Value, _>(input.as_bytes()).map(|v|console::format(&ctx, Rest(vec![v])).catch(&ctx){
  Ok(s) => println!("{s}"),
  Err(caught_err) => {
        match caught_err.into_value(ctx).map(|v|console.format(&ctx, Rest(vec![v]))){
           Ok(s) => eprintln!("Error: {s}"),
           Err(_) => eprintln!("Error: {:?}", caught_err)
        }
  }
}
```

2024-11-20 13:04 UTC, ahaoboy commented
> That way we can make it testable from rust.

I honestly have no idea how to test the repl, simulate keyboard input?

2024-11-20 15:06 UTC, richarddavison commented
> > That way we can make it testable from rust.
> 
> I honestly have no idea how to test the repl, simulate keyboard input?

No this can be simpler. Extract the processing of the line and just test that. We don't need to test capturing of std input.
In order to this we should probably move the entire repl capability from vm.rs and into a separate file (repl.rs). In there we can have like:
```rust
fn process_line(&line) -> std::result::Result<String,String>{
 //existing line processing logic but return strings for error and console rather than printing them stderr or stdout
}
```

And then we can test `process_line` with different input valid and invalid :) Hope it makes sense.

2024-11-22 13:53 UTC, richarddavison approved these changes
Nice thank you!

2024-11-22 13:53 UTC, merged