Add streams/web module
awslabs/llrt pull request #761
Opened 2024-12-31 18:27 UTC by jackkleeman

### Issue # (if available)

#544 

### Description of changes
This PR adds ReadableStream and WritableStream. TransformStream is still left to do. Almost all the WPT tests for these two objects are passing, with a couple commented out and explained.

Yes, this PR is very large. It is hard to avoid this as simply getting a working readable stream requires many functions to be implemented. If useful I can try to split out readable and writable although I don't think the line count is going to be much better - most of it is in readable anyway. 

I have tried to stay as faithful as possible to the spec (https://streams.spec.whatwg.org/) in the implementation. I have also borrowed occasionally from the reference implementation https://github.com/whatwg/streams/tree/main/reference-implementation for error messages and also for the pipeTo implementation which is not tightly defined by the spec.

I have removed the readable stream stub (`ReadableStream is not supported via global scope...`) as I found it was taking precedence over my implementation in tests. I still am not quite sure I understand the contexts/scopes in the wpt tests. Advice would be helpful.

I have yet not wired this up for use by other packages. It seems the existing llrt_stream implements a node stream for use in child process, and I don't think a web stream is appropriate there (unless we first implement a web <-> node conversion). We will want to have both stream and stream/web available for sure. The obvious first place to wire up would be fetch, though.

Great care is needed throughout to ensure that user objects are not held when we release control to the user, as they can do something re-entrant (ie, call one of those objects) and we will fail to obtain an owned borrow. The wpt tests do a very good job of finding these cases but there could be more and they create a panic. It seems ok if we put an experimental label on the streams/web package for the time being. The other thing to be aware of when releasing control is that the reader/writer may have changed from the one you had a handle on before which isn't necessarily a panic but can lead to bugs. Again, the wpt should catch a lot of these.

Key things for review:
1. Any changes outside of llrt_stream_web
2. Try it out

Possible optimizations:
1. pipeTo could have a more native impl instead of copying the JS reference implementation
3. Lots of places we use JS promises where we may be able to use Rust async code directly and skip some indirection
4. Various ctx.evals which just need to be cleaned up and replaced with ctx.global().get or similar

### Checklist

- [x] Created unit tests in `tests/unit` and/or in Rust for my feature if needed
- [x] Ran `make fix` to format JS and apply Clippy auto fixes
- [x] Made sure my code didn't add any additional warnings: `make check`
- [ ] Added relevant type info in `types/` directory
- [ ] Updated documentation if needed ([API.md](API.md)/[README.md](README.md)/Other)

_By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice._

2025-01-01 07:35 UTC, nabetti1720 commented
I think it's a great job. Just a comment. :)

> I have yet not wired this up for use by other packages. It seems the existing llrt_stream implements a node stream for use in child process, and I don't think a web stream is appropriate there (unless we first implement a web <-> node conversion). We will want to have both stream and stream/web available for sure. The obvious first place to wire up would be fetch, though.

Can you expose these classes from globalThis? That would make it more web standards compliant.
https://min-common-api.proposal.wintercg.org/

2025-01-01 15:22 UTC, jackkleeman commented
sure, thats easy to do

2025-01-03 02:05 UTC, nabetti1720 commented
> I have yet not wired this up for use by other packages. It seems the existing llrt_stream implements a node stream for use in child process, and I don't think a web stream is appropriate there (unless we first implement a web <-> node conversion). We will want to have both stream and stream/web available for sure. The obvious first place to wire up would be fetch, though.

As you say, I think support for fetch is the top priority.

The [Runtime compatibility](https://runtime-compat.unjs.io/) document that I often cite seems to check whether stream classes are supported using the following criteria:

```javascript
// reproduction.js
const judgement = (function () {
    if (!("fetch" in self)) {
        return { result: false, message: "fetch is not defined" };
    }
    var streamPromise = fetch("/favicon/favicon.ico")
        .then(function (response) {
            return response.body;
        })
        .catch(function () {
            return fetch(
                "https://mdn-bcd-collector.gooborg.com/favicon/favicon.ico"
            ).then(function (response) {
                return response.body;
            });
        });
    if (!streamPromise) {
        return { result: false, message: "streamPromise is falsy" };
    }
    var promise = streamPromise.then(function (stream) {
        return stream.getReader();
    });
    if (!promise) {
        return { result: false, message: "Promise variable is falsy" };
    }
    return promise.then(function (instance) {
        return !!instance;
    });
})();

console.log(await judgement);
```

When I checked it on my laptop, it seemed that some classes were determined to be "unsupported" because this code produced an error.
```
% llrt reproduction.js
TypeError: cannot read property 'getReader' of null
  at <anonymous> (/Users/shinya/Workspaces/llrt-test/reproduction.js:19:38)

% bun reproduction.js 
true
```

2025-01-03 03:06 UTC, Sytten commented
I will have to do a full review, but something that I saw that bugged me was the eval for creating errors. I am pretty sure we don't need to do that. We should be able to create them in Rust.

2025-01-03 09:56 UTC, jackkleeman commented
@nabetti1720 i think your code is testing whether fetch returns a stream as response.body, but it returns null:
```
  //FIXME return readable stream when implemented
    #[qjs(get)]
    pub fn body(&self) -> Null {
        Null
    }
```
lets get this merged first and i can look to wire it up with fetch

2025-01-03 11:40 UTC, richarddavison commented
Thanks @jackkleeman for this fantastic contribution 🎉 

> Various ctx.evals which just need to be cleaned up and replaced with ctx.global().get or similar

Like you mentioned, I see some ctx evals for error creation. Best approach here is to use primordials:
`BasePrimordials::get(ctx)?` where you have access to the type error constructor.
If this is something frequently done you can add a method to BasePrimodials:
`fn new_type_error(...)`

> Lots of places we use JS promises where we may be able to use Rust async code directly and skip some indirection

Can you elaborate a bit more on this?

2025-01-03 13:47 UTC, jackkleeman commented
I have now refactored all the ctx.global.get and ctx.eval into primordials. Currently new_type and new_range are just helper methods in my crate, if you want them to go into BasePrimordials let me know

re the promises. the spec has a lot of 'upon fulfillment of promise, do X'. i have a helper method upon_promise for this. the spec also asks that we convert promises into other promises by adding a fulfillment or rejection step. and the spec *also* asks that we set particular promises as 'handled' ie so they don't complain about unhandled rejections. given that the spec is quite specific, ive implemented things as faithfully as possible. this inevitably means calling .then and .catch a lot with anonymous Function::new() objects.

what i have not done (at all) is use rust async functions, convert promises into futures, etc. as far as i can tell, converting promises into rust futures still calls then and catch with a Function::new() under the hood, but just with a handle to a waker, allowing the previous async code to resume. so maybe performance wise this very similar, but the argument to use more rust async code might be that its easier to follow or more idiomatic. however, it will depart from the spec somewhat which could make it harder to debug, and imo it is a lot easier to accidentally hold a reference to a user object across an await point than it is to accidentally move one into a FnOnce that we execute on promise resolution. and as a reminder, holding references to user objects when we release to user code can lead to panics.

one special case s the pipeTo implementation, which is not actually defined in the spec (instead ive copied the reference implementation). i imagine that we could make that implementation simpler and more concise if we used rust futures more there, without the concern that it will depart from the spec.

2025-01-03 21:29 UTC, richarddavison requested changes
Some observations:
1. First of all, I can't thank you enough for this colossal effort! Huge work 🥇 
2. Great that we avoid accessing globals and use primordials instead (also safer as globals can be modified in user space). However, for perf reasons we should try to clone and store the primordial value in the struct when used frequently and when possible to avoid lookup. Even though primordial lookup is faster than global lookup, it's still expensive for frequent calls.
3. If possible, avoid using JS Function::new() if not providable from user space. This saves a ton of indication and we can pass fn pointers to rust functions instead. If accessible/definable from user space and from Rust, use an enum to hold either a JS Function, or a Rust function.
4. Maybe some macros would reduce duplication or simplify instanciantion where code is very similar but can't be refactored into a shared function LMKWYT?

2025-01-03 21:29 UTC, richarddavison commented on modules/llrt_stream_web/src/readable/tee.rs
> +}
We can create a typed array directly from rust:

`TypedArray::<u8>::new...`

2025-01-03 21:29 UTC, richarddavison commented on modules/llrt_stream_web/src/readable/tee.rs
> +            structured_clone: ctx.globals().get("structuredClone")?,
We can avoid this struct by calling rust function directly instead of using primordials.

2025-01-04 20:39 UTC, jackkleeman commented on modules/llrt_stream_web/src/readable/tee.rs
> +}
under the hood it just does this though?
```
    /// Convert from an ArrayBuffer
    pub fn from_arraybuffer(arraybuffer: ArrayBuffer<'js>) -> Result<Self>
    where
        T: TypedArrayItem,
    {
        let ctx = &arraybuffer.0.ctx;
        let ctor: Constructor = ctx.globals().get(T::CLASS_NAME)?;
        ctor.construct((arraybuffer,))
    }
```
so, better to use the constructor as we have a handle on it?

2025-01-04 20:40 UTC, jackkleeman commented on modules/llrt_stream_web/src/readable/tee.rs
> +            structured_clone: ctx.globals().get("structuredClone")?,
yes, this is to avoid an import loop issue. how can i get a method in llrt_core? i dont see any other modules doing so. i guess we can move it to util

2025-01-04 21:45 UTC, jackkleeman commented on modules/llrt_stream_web/src/readable/tee.rs
> +            structured_clone: ctx.globals().get("structuredClone")?,
ive moved to llrt_util

2025-01-05 12:04 UTC, jackkleeman commented
Re macros. I'll do a pass and think about what can be done. If you have any particular ideas let me know

2025-01-05 12:07 UTC, richarddavison commented on modules/llrt_stream_web/src/readable/tee.rs
> +}
True! We can change this later once https://github.com/DelSkayn/rquickjs/pull/407 is merged as it has fast paths to create typed arrays

2025-01-06 20:32 UTC, richarddavison commented
> I managed to shave off 700 lines with some new functions and type aliases but not seeing anything obvious beyond those - let me know if you see any

Fantastic, I'll take a second look!

2025-01-07 03:19 UTC, Sytten requested changes
This is a first pass on the review, I didn't yet get to `readable` and `writable` modules.
General comment is to please over-explain everything for future maintainers and split unrelated items into different files.

2025-01-07 03:19 UTC, Sytten commented on modules/llrt_stream_web/src/queueing_strategy.rs
> +            None => Ok(default_hwm),
```rust
Some(Self { high_water_mark: Some(high_water_mark), .. }) => { ...}
_ => Ok(default_hwm)
```

2025-01-07 03:19 UTC, Sytten commented on modules/llrt_stream_web/src/queueing_strategy.rs
I am huge fan of splitting things into smaller files instead of one big files. Lets create a module here with the different strategies and we can have the helpers in the root. We will also need documentation around the `SizeFunction`. Took me a few passes to understand why that was written that way (like size not actually taking a chunk but returning a callable class). I feel like this could be simplified but for now good enough to add some comments and at least split them from the strategy implementation.

2025-01-07 03:22 UTC, Sytten commented
Also please write the typescript typing, I did write a simplified version of it since we didnt have most of the API but now that we do we should mostly probably take back the node typing and put it in there.

2025-01-07 03:23 UTC, Sytten commented on modules/llrt_stream_web/src/queueing_strategy.rs
> +        this: Option<QueuingStrategy<'js>>,
Same for the other method below this one

2025-01-07 09:20 UTC, jackkleeman commented on modules/llrt_stream_web/Cargo.toml
> +name = "llrt_stream_web"
i don't think we can replace the existing package entirely, because you will probably still need node-streams for compatbitility with other node libraries like fs

2025-01-07 09:25 UTC, jackkleeman commented on modules/llrt_exceptions/src/lib.rs
> +        let code = match name.as_str() {
i am not sure what you mean, i agree domexception isnt native to quickjs, but the wpt tests for streams expect that domexceptions on abort will have the code set correctly

2025-01-07 12:11 UTC, Sytten commented on modules/llrt_stream_web/Cargo.toml
> +name = "llrt_stream_web"
Right make sense, do we think we could reuse code from this package in the node implementation?

2025-01-07 12:12 UTC, Sytten commented on modules/llrt_exceptions/src/lib.rs
> +        let code = match name.as_str() {
What I mean is that if we want to throw those errors from rust we will need those names as constants somewhere

2025-01-07 12:34 UTC, jackkleeman commented on modules/llrt_stream_web/Cargo.toml
> +name = "llrt_stream_web"
i think its somewhat unlikely, they have quite different semantics

2025-01-07 13:55 UTC, jackkleeman commented on modules/llrt_stream_web/src/lib.rs
> +/// Helper type for treating an undefined value as None, but not null
Null exists in rquickjs but it doesn't actually have IntoJs implemented on it which probably is an accident. Undefined doesn't exist - there is an impl for Option, but it accepts Null as None which is not what we want.

2025-01-07 14:23 UTC, jackkleeman commented on modules/llrt_exceptions/src/lib.rs
> +        let code = match name.as_str() {
yes, i suppose so. currently it seems we are just using string literals to do so

2025-01-07 22:41 UTC, Sytten reviewed
Some further comments

2025-01-07 22:42 UTC, Sytten commented
Sorry the lines of the comments are off due to the force push, I did the review this morning

2025-01-07 22:46 UTC, Sytten commented on modules/llrt_stream_web/src/readable/iterator.rs
> +    end_of_iteration: Symbol<'js>,
This is referring to the eval calls

2025-01-08 01:08 UTC, Sytten commented on modules/llrt_stream_web/src/readable/mod.rs
> +        options: Opt<Value<'js>>,
That was supposed to be 110-113

2025-01-08 11:06 UTC, jackkleeman commented
I believe we do support everything in there but good to double check. SOunds good

2025-01-08 11:20 UTC, jackkleeman commented on modules/llrt_stream_web/src/readable/iterator.rs
> +            None => return_steps(ctx.clone(), &iterator)?,
more specifically, it only supports the default controller case, and default controller can only have a default reader. we have no way of knowing what type of object an iterator returns (and its not guaranteed to stay the same) so a byte controller isnt possible

2025-01-08 11:21 UTC, jackkleeman commented on modules/llrt_stream_web/src/readable/iterator.rs
> +    end_of_iteration: Symbol<'js>,
yeah, without a new quickjs api i see no other option here

2025-01-08 11:25 UTC, jackkleeman commented on modules/llrt_stream_web/src/readable/iterator.rs
> +        rquickjs::class::impl_::CloneTrait<Self>,
is the engine send?? i have been using Rc all over the place so I don't see how my objects can be moved between threads. in fact i was thinking atomicbool is technically not necessary and I could use Cell<bool> wherever I use it. But in practice this is pretty similar to AtomicBool with relaxed.

2025-01-08 11:26 UTC, jackkleeman commented on modules/llrt_stream_web/src/readable/iterator.rs
> +
the only goal is atomic update of the bool within the same thread. if all these types need to be Send, then I have lots of other things to fix.

2025-01-08 11:30 UTC, jackkleeman commented on modules/llrt_stream_web/src/readable/mod.rs
> +    // readonly attribute boolean locked;
> My problem with OwnedBorrowMut is that it can easily bite you with a panic if you try to borrow mutably in two different places or if you try to borrow mut and there is already a read-only reference.
Yes, I am very well acquainted with this!

These panics imply an implementation issue (generally something re-entrant where we call out to user code and they call back in), not a user error, so I don't know if an exception is valid. An exception can leave the stream in an invalid state as these functions are generally not supposed to throw exceptions. IMO given this is a new feature its correct to panic on implementation issues.

2025-01-08 11:33 UTC, jackkleeman commented on modules/llrt_stream_web/src/readable/mod.rs
> +                        .get::<_, Function<'js>>("valueOf")?
generally I have left things as values so that we can error exactly when the spec says we should error - the wpt tests will check that we throw for some parameter issues before other issues. I can play around with this particular case but if you see me doing odd things with Value<'js> thats typically why. Obviously I would prefer to store/accept the actual desired type where possible

2025-01-08 11:40 UTC, jackkleeman commented on modules/llrt_stream_web/src/readable/mod.rs
> +        let options = match options.0 {
I know, but lets be specific about how that can happen - *only* if we hold this borrow across a point where we call into user code, or store it (eg by accidentally capturing it into a closure). Those are the things we must not do - and we want to notice immediately if we do (imo panicking is acceptable). If we don't do those things, I don't see how its possible for the borrow to be already held, given that this is a single threaded runtime so there cannot be two simultaneous function calls.

These types have to be moved constantly and (occasionally) turned back into classes for when we call use code or store them. There are extremely few functions that require a non-mutable access or an access that doesn't require the ability to turn into a class. OwnedBorrowMut is the most suitable type to pass around for those reasons - a BorrowMut guard or a &mut can't be turned back into a class, and OwnedBorrow isn't mutable.

2025-01-08 11:41 UTC, jackkleeman commented on modules/llrt_stream_web/src/readable/mod.rs
> +            Some(signal) => match Class::<'js, AbortSignal>::from_js(&ctx, signal) {
as said elsewhere, that may not be true as we often need to throw a TypeError at the 'correct' time according to the wpt. I can check for this particular case

2025-01-08 11:43 UTC, jackkleeman commented on modules/llrt_stream_web/src/readable/mod.rs
> +            ctx.clone(),
technically many of the promise primordials uses are as 'hot' as can be as they happen on essentially every chunk that passes through. 

I wonder if we could have a thread-local map where we can look up primordials indexed against the ctx reference. Then you only have to pay the ctx.userdata lookup once per thread, and after that can use a nice local variable.

2025-01-08 11:44 UTC, jackkleeman commented on modules/llrt_stream_web/src/readable/objects.rs
> +}
the derive macro mistakenly requires that C and R implement Clone, which they don't, and don't need to.

2025-01-08 11:45 UTC, jackkleeman commented on modules/llrt_stream_web/src/readable/objects.rs
> +impl<'js, C: ReadableStreamController<'js>, R: ReadableStreamReader<'js>> Trace<'js>
the derive macro mistakenly requires that C and R implement Trace, which they don't, and don't need to.

2025-01-08 12:04 UTC, jackkleeman commented on modules/llrt_stream_web/src/readable/mod.rs
> +        ctx: Ctx<'js>,
I think would have to be a macro because we can't just return an error, we have to specifically return a Ok(promise)

2025-01-08 12:20 UTC, jackkleeman commented on modules/llrt_stream_web/src/readable/mod.rs
> +        ctx: Ctx<'js>,
actually i have an idea

2025-01-08 15:44 UTC, jackkleeman commented on modules/llrt_stream_web/src/readable/mod.rs
> +            Some(signal) => match Class::<'js, AbortSignal>::from_js(&ctx, signal) {
in this case it seems possible

2025-01-08 15:54 UTC, jackkleeman commented on modules/llrt_stream_web/src/readable/iterator.rs
> +        rquickjs::class::impl_::CloneTrait<Self>,
ok, im going to make everything send and i will sort out the bools

2025-01-08 22:02 UTC, richarddavison commented on modules/llrt_stream_web/src/readable/iterator.rs
> +    end_of_iteration: Symbol<'js>,
Agree and I'll ask their opinion.  Today its very clunky to work with JS iterators

2025-01-08 22:07 UTC, richarddavison commented on modules/llrt_exceptions/src/lib.rs
> +        let code = match name.as_str() {
Maybe an enum for this? The enum can have unit variants which would then mean the discriminant can be equal 
to the code. Something like:
```rust
let exception_as_value = DomException::IndexSizeError.value(&ctx)
//or throw exception
Err(DomException::IndexSizeError.throw(&ctx)
```

2025-01-09 00:47 UTC, Sytten commented on modules/llrt_stream_web/src/readable/mod.rs
> +            ctx.clone(),
Thread local would not work in parallel mode though. Probably best to ignore.

2025-01-09 09:05 UTC, jackkleeman commented on modules/llrt_stream_web/src/readable/mod.rs
> +            ctx.clone(),
it would, it just would be more expensive (one primordial lookup per thread)

2025-01-10 18:25 UTC, richarddavison commented on modules/llrt_exceptions/src/lib.rs
> +        let code = match name.as_str() {
@jackkleeman what do you think? 👆 I’m also fine doing this improvement after we land this one. It’s already big enough as is. Up to you

2025-01-10 18:47 UTC, jackkleeman commented on modules/llrt_exceptions/src/lib.rs
> +        let code = match name.as_str() {
oh sorry missed this. yeah will do

2025-01-12 11:17 UTC, jackkleeman commented on modules/llrt_exceptions/src/lib.rs
> +        let code = match name.as_str() {
done!

2025-01-13 07:37 UTC, richarddavison requested changes
Thanks! Some comments:

1. We can store the string as we already have a string reference from JS and then use DOMExceptionName as a validation mechanism (and great to have when calling from rust)
2. Remove code property (hard code to 0) as it's deprecated and should be used.

2025-01-13 07:37 UTC, richarddavison commented on modules/llrt_exceptions/src/lib.rs
> +#[derive(rquickjs::class::Trace, Debug)]
We don't need to trace this, contains no Js refs

2025-01-13 07:37 UTC, richarddavison commented on modules/llrt_exceptions/src/lib.rs
> +            DOMExceptionName::Other(_) => 0,
We can avoid this type as DOMExceptionName should always be Error if we can't find a matching type. To be honest I think we can drop the code entirely since it's deprecated and return 0:
https://developer.mozilla.org/en-US/docs/Web/API/DOMException/code
There is also some missing names:
https://developer.mozilla.org/en-US/docs/Web/API/DOMException#error_names

2025-01-13 07:37 UTC, richarddavison commented on modules/llrt_exceptions/src/lib.rs
> +impl From<String> for DOMExceptionName {
Since the error code enum name and string representation are the same we can probably use a macro here to create the From<...>. We can also avoid the `as_str` fn by storing the string value in the class so we can avoid looking up the value again.

2025-01-13 07:37 UTC, richarddavison commented on modules/llrt_exceptions/src/lib.rs
> +    name: DOMExceptionName,
Store the string value: DOMExceptionName is just used for validation and type safety.

2025-01-13 09:56 UTC, jackkleeman commented on modules/llrt_exceptions/src/lib.rs
> +            DOMExceptionName::Other(_) => 0,
The code is checked for in wpt tests. Thats the reason I added all of this in the first place! I didn't include names that don't have a code, but I suppose I can

2025-01-13 10:06 UTC, jackkleeman commented on modules/llrt_exceptions/src/lib.rs
> +            DOMExceptionName::Other(_) => 0,
> We can avoid this type as DOMExceptionName should always be Error if we can't find a matching type
is that true? I didn't spot it in the spec

2025-01-13 10:10 UTC, jackkleeman commented on modules/llrt_exceptions/src/lib.rs
> +            DOMExceptionName::Other(_) => 0,
note also:
```
> new DOMException("a", "").name
''
> new DOMException("a").name
'Error'
```

2025-01-13 10:14 UTC, jackkleeman commented on modules/llrt_exceptions/src/lib.rs
> +impl From<String> for DOMExceptionName {
i think only with a proc macro, or by bringing in something like derive_more. Is there a library you've used elsewhere that you're happy for me to bring in?

2025-01-13 15:07 UTC, richarddavison commented on modules/llrt_exceptions/src/lib.rs
> +            DOMExceptionName::Other(_) => 0,
My misstake you're right, It should only be "Error" if second argument is undefined/missing.
`new DOMException("a", null).name` also works. So Opt<Coerced<String>> takes care of that

2025-01-13 15:24 UTC, richarddavison requested changes

2025-01-13 15:24 UTC, richarddavison commented on modules/llrt_exceptions/src/lib.rs
> +impl From<String> for DOMExceptionName {
No need to use proc macros if we define the enum in the macro.

https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=8c994023707f819dd206cad76adf281b

2025-01-13 20:44 UTC, jackkleeman commented
I decided to just bite the bullet and add the DOMException wpt tests

2025-01-16 08:14 UTC, richarddavison approved these changes

2025-01-16 15:26 UTC, richarddavison commented on modules/llrt_stream_web/src/readable/iterator.rs
> +        let cls = Class::<Self>::instance(ctx.clone(), self)?;
That would be awesome but is out of scope for this already huge PR. Let's do it for streams improvments

2025-01-16 15:27 UTC, richarddavison commented on modules/llrt_stream_web/src/readable/mod.rs
> +            ctx.clone(),
I'll leave this as is for now. Primordials is not only for caching lookups but also prevents monkey patches. We can work on perf improvements later

2025-01-16 15:29 UTC, richarddavison commented on modules/llrt_stream_web/src/lib.rs
> +pub fn init(ctx: &Ctx) -> Result<()> {
Yeah, i'll fix this in another PR where we do lookup from global or initialize.

2025-01-16 20:02 UTC, merged

2025-01-19 12:01 UTC, jackkleeman commented
thanks for the review - i know it was a big one
will keep chipping away at some of the smaller tasks like transform stream and encoder/decoder :)